version: "3"

services:
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_value:/var/lib/postgresql/data/

  prerun:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        sleep 10 
        python manage.py migrate
        python manage.py collectstatic --noinput
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_value:/app/static/.

  backend:
    build:
      context: .
    restart: always
    command: gunicorn lenta.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - prerun
    container_name: lenta_backend

  nginx:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - static_value:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  db_value:
  static_value:
